spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Nayan@2002

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
logging:
  level:
    org.springframework: WARN
    org.flywaydb: INFO

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: false
#    open-in-view: false
#logging:
#  level:
#    org.springframework: ERROR